on: 
    issues:
        types: [opened]

name: Open Jira Issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Issue Opener
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
          project: ASESP
          issuetype: Bug
          summary: '${{ github.event.issue.title }}'
          description: ${{ github.event.issue.body }} \\ \\ _Created from GitHub Action_ for ${{ github.event.issue.html_url }}

