name: Build `tfm` - Cross Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Install gox
        run: |
          go get github.com/mitchellh/gox 
          go install github.com/mitchellh/gox 
      - name: Install zip
        run: |
          sudo apt-get update -q
          sudo apt-get install zip -q

      - name: Cross compile
        run: |
          gox \
            -os="linux darwin windows" \
            -ldflags="-X 'github.com/hashicorp-services/tfm/version.Build=${{ github.sha }}' -X 'github.com/hashicorp-services/tfm/version.Date=$(date)' -X 'github.com/hashicorp-services/tfm/version.BuiltBy=github'" \
            -arch="amd64 arm64" \
            -output "./pkg/{{.OS}}_{{.Arch}}/tfm" \
            .
      - name: Print version
        run: ./pkg/linux_amd64/tfm --version
        
      # Package all binaries together
      - uses: actions/upload-artifact@v2
        with:
          name: tfm-artifacts
          path: ./pkg/*     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}